/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashIndexRouteImport } from './routes/_dash/index'
import { Route as DashApplicationsRouteImport } from './routes/_dash/applications'
import { Route as DashDomainsRouteImport } from './routes/_dash/domains'
import { Route as DashFlowsRouteImport } from './routes/_dash/flows'
import { Route as DashProcessingRouteImport } from './routes/_dash/processing'
import { Route as DashRulesRouteImport } from './routes/_dash/rules'
import { Route as DashSystemRouteImport } from './routes/_dash/system'
import { Route as DashTrafficRouteImport } from './routes/_dash/traffic'
import { Route as ApiDpiSplatRouteImport } from './routes/api/dpi/$'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashApplicationsRoute = DashApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashRoute,
} as any)
const DashDomainsRoute = DashDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashRoute,
} as any)
const DashFlowsRoute = DashFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashRoute,
} as any)
const DashProcessingRoute = DashProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => DashRoute,
} as any)
const DashRulesRoute = DashRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashRoute,
} as any)
const DashSystemRoute = DashSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashRoute,
} as any)
const DashTrafficRoute = DashTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => DashRoute,
} as any)
const ApiDpiSplatRoute = ApiDpiSplatRouteImport.update({
  id: '/api/dpi/$',
  path: '/api/dpi/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/applications': typeof DashApplicationsRoute
  '/domains': typeof DashDomainsRoute
  '/flows': typeof DashFlowsRoute
  '/processing': typeof DashProcessingRoute
  '/rules': typeof DashRulesRoute
  '/system': typeof DashSystemRoute
  '/traffic': typeof DashTrafficRoute
  '/api/dpi/$': typeof ApiDpiSplatRoute
}
export interface FileRoutesByTo {
  '/applications': typeof DashApplicationsRoute
  '/domains': typeof DashDomainsRoute
  '/flows': typeof DashFlowsRoute
  '/processing': typeof DashProcessingRoute
  '/rules': typeof DashRulesRoute
  '/system': typeof DashSystemRoute
  '/traffic': typeof DashTrafficRoute
  '/': typeof DashIndexRoute
  '/api/dpi/$': typeof ApiDpiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/_dash/applications': typeof DashApplicationsRoute
  '/_dash/domains': typeof DashDomainsRoute
  '/_dash/flows': typeof DashFlowsRoute
  '/_dash/processing': typeof DashProcessingRoute
  '/_dash/rules': typeof DashRulesRoute
  '/_dash/system': typeof DashSystemRoute
  '/_dash/traffic': typeof DashTrafficRoute
  '/_dash/': typeof DashIndexRoute
  '/api/dpi/$': typeof ApiDpiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/domains'
    | '/flows'
    | '/processing'
    | '/rules'
    | '/system'
    | '/traffic'
    | '/api/dpi/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/applications'
    | '/domains'
    | '/flows'
    | '/processing'
    | '/rules'
    | '/system'
    | '/traffic'
    | '/'
    | '/api/dpi/$'
  id:
    | '__root__'
    | '/_dash'
    | '/_dash/applications'
    | '/_dash/domains'
    | '/_dash/flows'
    | '/_dash/processing'
    | '/_dash/rules'
    | '/_dash/system'
    | '/_dash/traffic'
    | '/_dash/'
    | '/api/dpi/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
  ApiDpiSplatRoute: typeof ApiDpiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/applications': {
      id: '/_dash/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof DashApplicationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/domains': {
      id: '/_dash/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DashDomainsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/flows': {
      id: '/_dash/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof DashFlowsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/processing': {
      id: '/_dash/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof DashProcessingRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/rules': {
      id: '/_dash/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof DashRulesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/system': {
      id: '/_dash/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof DashSystemRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/traffic': {
      id: '/_dash/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof DashTrafficRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/dpi/$': {
      id: '/api/dpi/$'
      path: '/api/dpi/$'
      fullPath: '/api/dpi/$'
      preLoaderRoute: typeof ApiDpiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashRouteChildren {
  DashApplicationsRoute: typeof DashApplicationsRoute
  DashDomainsRoute: typeof DashDomainsRoute
  DashFlowsRoute: typeof DashFlowsRoute
  DashProcessingRoute: typeof DashProcessingRoute
  DashRulesRoute: typeof DashRulesRoute
  DashSystemRoute: typeof DashSystemRoute
  DashTrafficRoute: typeof DashTrafficRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashApplicationsRoute: DashApplicationsRoute,
  DashDomainsRoute: DashDomainsRoute,
  DashFlowsRoute: DashFlowsRoute,
  DashProcessingRoute: DashProcessingRoute,
  DashRulesRoute: DashRulesRoute,
  DashSystemRoute: DashSystemRoute,
  DashTrafficRoute: DashTrafficRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
  ApiDpiSplatRoute: ApiDpiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
